name: Deploy main
on:
  push:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: make install

      - name: Deploy
        run: make deploy
